apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 71-motd-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/motd
          mode: 0444
          overwrite: true
          user:
            name: root
          group:
            name: root
          contents:
            source: data:text/plain;charset=utf-8;base64,VGhlIHByb2dyYW1zIGluY2x1ZGVkIHdpdGggdGhlIERlYmlhbiBHTlUvTGludXggc3lzdGVtIGFyZSBmcmVlIHNvZnR3YXJlOgp0aGUgZXhhY3QgZGlzdHJpYnV0aW9uIHRlcm1zIGZvciBlYWNoIHByb2dyYW0gYXJlIGRlc2NyaWJlZCBpbiB0aGUKaW5kaXZpZHVhbCBmaWxlcyBpbiAvdXNyL3NoYXJlL2RvYy8qL2NvcHlyaWdodC4KCkRlYmlhbiBHTlUvTGludXggY29tZXMgd2l0aCBBQlNPTFVURUxZIE5PIFdBUlJBTlRZLCB0byB0aGUgZXh0ZW50CnBlcm1pdHRlZCBieSBhcHBsaWNhYmxlIGxhdy4K

