apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 71-motd-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/motd
          mode: 0444
          filesystem: root
          overwrite: true
          user:
            name: root
          group:
            name: root
          contents:
            source: data:text/plain;charset=utf-8;base64,IF9fXyAgX19fXyAgX19fXyAgX18gIF9fXwogLyBfIFwvIF9fIFwvIF9fIFwvICB8LyAgLwovICBfXy8gL18vIC8gLyAvIC8gL3xfLyAvIApcX19fL1xfX19fL18vIC9fL18vICAvXy8gIAoKV2VsY29tZSB0byB0aGUgTm9kZSEK
